#API Gateway
# gateway:
  # image: fagongzi/gateway
  # restart: always
  # ports:
    # - 80:80
    # - 8080:8080
    # - 8081:8081

# Redis Message Queue
redis-pubsub:
  image: bitnami/redis:latest
  environment:
    - ALLOW_EMPTY_PASSWORD=yes
  ports:
    - 6379:6379
     
#Crawer Database
mongo-crawer:
  image: tutum/mongodb:3.0
  environment:
    - AUTH=no
    - JOURNALING=no 
  ports:
    - 27017:27017 
    - 28017:28017 
     
#Crawer 
crawer:
  image: lixiepeng/python_env:latest
  #build: crawer/
  restart: always
  links:
    - redis-pubsub
    - mongo-crawer
  volumes:
    - ./crawer:/code
  command: [ "python","craw_worker.py"]

#Redis Text Analysis DB
redis-text:
  image: bitnami/redis:latest
  environment:
    - ALLOW_EMPTY_PASSWORD=yes
  ports:
    - 6380:6379

# Text Analysis
text:
  image: lixiepeng/python_env:latest
  #build: text/
  restart: always
  ports:
    - 5001:5000
  links:
    - redis-pubsub
    - mongo-crawer
    - redis-text
  volumes:
    - ./text:/code
  command: python text_manager.py
  
# cpu_shares: 73
# cpu_quota: 50000
# cpuset: 0,1

# user: postgresql
# working_dir: /code

# domainname: foo.com
# hostname: foo
# ipc: host
# mac_address: 02:42:ac:11:65:43

# mem_limit: 1000000000
# memswap_limit: 2000000000
# privileged: true

# restart: always

# read_only: true
# shm_size: 64M
# stdin_open: true
# tty: true
