#API Gateway
# gateway:
  # image: fagongzi/gateway
  # restart: always
  # ports:
    # - 80:80
    # - 8080:8080
    # - 8081:8081

# Redis Message Queue
# redis-pubsub:
  # image: bitnami/redis:latest
  # environment:
    # - ALLOW_EMPTY_PASSWORD=yes
  # ports:
    # - 6379:6379
    
#Crawer Proxy
# proxy-pool:
  # build: proxy_pool/
  # restart: always
  # ports:
    # - 5000:5000
  # command: [ "python","./Run/main.py"]
ProxyPool:
  build: ProxyPool/
  restart: always
  ports:
    - 8000:8000
  command: [ "python","proxypool.py"]
     
#Crawer Database
# mongo-crawer:
  # image: tutum/mongodb:3.0
  # environment:
    # - AUTH=no
    # - JOURNALING=no 
  # ports:
    # - 27017:27017 
    # - 28017:28017 
     
#Crawer 
# crawer:
  # build: crawer/
  # restart: always
  # links:
    # - redis-pubsub
    # - mongo-crawer
    # - ProxyPool
  # command: [ "python","craw_worker.py"]

#Redis Text Analysis DB
# redis-text:
  # image: bitnami/redis:latest
  # environment:
    # - ALLOW_EMPTY_PASSWORD=yes
  # ports:
    # - 6380:6379

# Text Analysis
# text:
  # build: text/
  # restart: always
  # ports:
    # - 5001:5000
  # links:
    # - redis-pubsub
    # - mongo-crawer
    # - redis-text
  # command: [ "python","text_web.py","python","text_worker.py"]
