# Load Balancing
consul:
  image: progrium/consul:latest
  command: -server -bootstrap -ui-dir /ui
  restart: always
  mem_limit: 128m
  ports:
    - 8500:8500
  expose:
    - 53
    - 8300
    - 8301
    - 8302
    - 8400
    - 8500
  dns:
    - 127.0.0.1
      
# Kong Database

kong-database:
  image: postgres:9.4
  ports:
    - 5432
  environment:
    - POSTGRES_USER=kong
    - POSTGRES_DB=kong

# Kong

kong:
  image: lixiepeng/kong-docker:latest
  restart: always
  links:
    - kong-database:kong-database
    - consul
  ports:
    - 8000
    - 8443
    - 8001
  ports:
    - 8000:8000
    - 8443:8443
    - 8001:8001
  expose:
    - 7946
    - 7946/udp
  environment:
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=kong-database

# Kong-dashboard

kong-dashboard:
  image: pgbi/kong-dashboard:v2
  restart: always
  ports:
    - 8081:8080 

#Redis Message Queue

redis-pubsub:
  image: bitnami/redis:latest
  environment:
    - ALLOW_EMPTY_PASSWORD=yes
  ports:
    - 6379:6379
     
#Crawer Database

mongo-crawer:
  image: tutum/mongodb:3.0
  environment:
    - AUTH=no
    - JOURNALING=no 
  ports:
    - 27017:27017 
    - 28017:28017 
     
#Crawer 

crawer:
  image: lixiepeng/python_env:latest
  restart: always
  links:
    - redis-pubsub
    - mongo-crawer
  volumes:
    - ./crawer:/code
  command: [ "python","craw_worker.py"]

#Redis Text Analysis DB

redis-text:
  image: bitnami/redis:latest
  environment:
    - ALLOW_EMPTY_PASSWORD=yes
  ports:
    - 6380:6379

# Text Analysis

text:
  image: lixiepeng/python_env:latest
  restart: always
  ports:
    - 5001:5000
  links:
    - redis-pubsub
    - mongo-crawer
    - redis-text
  volumes:
    - ./text:/code
  command: python text_manager.py